### ISSUE TITLE
[BUG / Error] yarn problem

### ISSUE THREAD

**Issue by XiNaru** [finnie2006/PteroFreeStuffinstaller#61]
Hey i have a little problem .
i want install the addon pma button
but yarn dont want.

i have pterodactyl 1.11.5
and here the error

--2024-01-01 07:58:44--  https://raw.githubusercontent.com/Sigma-Production/PteroFreeStuffinstaller/V1.10.1/resources/phpmyadmin/DatabaseRow.tsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9570 (9.3K) [text/plain]
Saving to: ‘DatabaseRow.tsx’

DatabaseRow.tsx                                 100%[======================================================================================================>]   9.35K  --.-KB/s    in 0s

2024-01-01 07:58:44 (86.4 MB/s) - ‘DatabaseRow.tsx’ saved [9570/9570]

yarn run v1.22.21
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/pterodactyl/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/pterodactyl/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.19.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

   INFO  Application is now live.

phpMyAdmin successfully installed (but there is no button)

**Comment by Lovinoes** [comment]
For NodeJS version 17 and above, you must enable the --openssl-legacy-provider option before building.

run `export NODE_OPTIONS=--openssl-legacy-provider` and re-run the script
